name: 编译部署

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: 编译部署
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: 拉取代码
              uses: actions/checkout@v2

            - name: 搭建环境
              uses: actions/setup-node@v2
              with:
                  cache: yarn

            - name: 安装依赖
              run: yarn --frozen-lockfile

            - name: 编译项目
              run: yarn vite build

            - name: 部署项目
              run: |
                  cd dist
                  git init
                  git add .
                  git commit -m 'update'
                  git push git@github.com:fanqianduan/layon.git HEAD:gh-pages -f
